version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    # Optional:: for more verbose logs for debugging
    command: [ "postgres", "-c", "log_statement=all" ]

    ports:
      - "5500:5432"

  # Optional - Caching
  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      # The pipe indicates that this variable contains multiline values
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      # Optional - For applications that interact with Mailing Servers
      # Mailing server credentials
      - SMTP_HOST=
      - FROM_EMAIL=
      - SMTP_KEY=
    ports:
      - "4000:8000"
    # Optional - Volume mapping
    volumes:
      - ./:/app
